{% set version = "0.2.8" %}

package:
  name: r-worrms
  version: {{ version }}

source:
  fn: worrms_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/worrms_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/worrms/worrms_{{ version }}.tar.gz
  sha256: 43c1273b6321d6b7f62c5f101ee1626a3e1b7d08f9990b9dfa5a0d65e24cef08

build:
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-crul >=0.3.6
    - r-data.table
    - r-jsonlite >=1.1
    - r-tibble >=1.2
  run:
    - r-base
    - r-crul >=0.3.6
    - r-data.table
    - r-jsonlite >=1.1
    - r-tibble >=1.2

test:
  commands:
    - $R -e "library('worrms')"  # [not win]
    - "\"%R%\" -e \"library('worrms')\""  # [win]

about:
  home: https://cran.r-project.org/package=worrms
  license: MIT
  license_file: LICENSE
  summary: Client for World Register of Marine Species

extra:
  recipe-maintainers:
    - ocefpaf
