appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: un/uTGny6zqf4qwSL8redToCbSHymaPW0S8u30NHS3nxQ9tIPQ7xea6biyYo3m+oAlKckKeGgjjrYHLA/4oAdHoMseukMdKM1oFScE3Rs6mV7vtLLcOsjrn+AbXOXMW1fnnIkjj7JBEh2ufB5uK8/BO/5Vi+VDL5vuBqOBovnqPvL0vmdyI9qF2/+lq6y8pkZK+IDX08+ykoZXI8bc8KJHlYuPgLz115XnDuSQ/zA5LdmkJwjHR8e/duPZFi5hMaV4Yhan1mFe2D4rpPl0r1GNwpmRNlc0frfjZTnxwEdfbdfO4gAn5LjJmXmDwBTaZL8GApsDC3h2Gw0f5Pv9yrtKHogjQBYKTeMzjWldui+dHsFRKGrhcoElqQzH9Ie/B9G50eEwP/hdHr15qjrHJcdhLgYcBtE5oNpUnpkGwrB6akv/EMacDHyKEPqIPtcA1Ij6kzvIiv95Zbpjc6lfk0fvNAKi4nll8kQ4rNvjdclspqe996cgOBuw7DouLxHxG+QNx1unkixprlrurnCuF6D48iT0W+kdC1f71fblyxuKGAXbczq50zUEjcc1Og4qn63EiLJ4H1CQV+kh0Lmj4/3PhaQqkVv8d1qoHRgkazkI+nZevMV0PK8lc48NuChb6dQZBpisQjEQDiIUNrxmm6eniQvzBvkbtjhySEI3x6Leo=
conda_forge_output_validation: false
